[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.18"
remappings = [
    "forge-std/=lib/forge-std/src/",
    "ERC721A/=lib/ERC721A/contracts/"
]

[profile.fuzz]
runs = 5
max_test_rejects = 100000

[etherscan]
base-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
